apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /home/oys/kind-testbed/mounts/share
    containerPath: /mnt/share
    #
    # add an additional mount leveraging *all* of the config fields
    #
    # generally you only need the two fields above ...
    #
- role: worker
  extraMounts:
  - hostPath: /home/oys/kind-testbed/mounts/share
    containerPath: /mnt/share
    # optional: if set, the mount is read-only.
    # default false
    # readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    # selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    #
    # WARNING: You very likely do not need this field.
    #
    # This field controls propagation of *additional* mounts created
    # *at runtime* underneath this mount.
    #
    # On MacOS with Docker Desktop, if the mount is from macOS and not the
    # docker desktop VM, you cannot use this field. You can use it for
    # mounts to the linux VM.
    # propagation: None
- role: worker
  extraMounts:
  - hostPath: /home/oys/kind-testbed/mounts/share
    containerPath: /mnt/share

